import type { Prescription } from '../../../Types/types';

const prescriptionMocks: Prescription[] = [
  {
    id: '6',
    name: 'Simvastatin',
    dosage: '20mg',
    frequency: 'Once daily',
    dateIssued: '2024-05-01',
    expiryDate: '2025-12-01',
    medicationType: 'tablet',
    remainingRefills: 2,
    instructions: 'Take in the evening',
    prescribedBy: 'Dr. Alice Morgan',
    pharmacy: 'Greenway Pharmacy',
  },
  {
    id: '1',
    name: 'Amoxicillin',
    dosage: '500mg',
    frequency: 'Three times a day',
    dateIssued: '2023-05-10',
    expiryDate: '2023-11-10',
    medicationType: 'capsule',
    remainingRefills: 2,
    instructions: 'Take with food',
    prescribedBy: 'Dr. Emily Johnson',
    pharmacy: 'Healthera Pharmacy',
  },
  {
    id: '2',
    name: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Once daily',
    dateIssued: '2023-06-15',
    expiryDate: '2024-06-15',
    medicationType: 'tablet',
    remainingRefills: 5,
    instructions: 'Take in the morning',
    prescribedBy: 'Dr. Robert Chen',
    pharmacy: 'Central Pharmacy',
  },
  {
    id: '3',
    name: 'Ventolin',
    dosage: '100mcg',
    frequency: 'As needed',
    dateIssued: '2023-04-20',
    expiryDate: '2024-04-20',
    medicationType: 'inhaler',
    remainingRefills: 3,
    instructions: 'Use as directed for shortness of breath',
    prescribedBy: 'Dr. Sarah Williams',
    pharmacy: 'Healthera Pharmacy',
  },
  {
    id: '4',
    name: 'Metformin',
    dosage: '850mg',
    frequency: 'Twice daily',
    dateIssued: '2023-07-01',
    expiryDate: '2024-01-01',
    medicationType: 'tablet',
    remainingRefills: 0,
    instructions: 'Take with meals',
    prescribedBy: 'Dr. Emily Johnson',
    pharmacy: 'Downtown Drugs',
  },
  {
    id: '5',
    name: 'Atorvastatin',
    dosage: '20mg',
    frequency: 'Once daily',
    dateIssued: '2023-05-25',
    expiryDate: '2024-05-25',
    medicationType: 'tablet',
    remainingRefills: 4,
    instructions: 'Take in the evening',
    prescribedBy: 'Dr. Robert Chen',
    pharmacy: 'Central Pharmacy',
  },
];

export default prescriptionMocks;
